# -*- coding: utf-8 -*-
"""Python Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-B2HpAihPLJ2GpELWAXsX5wO4jnrD3qk
"""

print('Hello World','Hello SRDT', sep=' ' , end='\n')
print('Hello bro')

print(10%3) # Modulus, Remainder
print(10//3) # Quotient
print(10**3) #** Raises power on a number

"""CALCULATOR SAMPLE"""

a = 10;
b = 12;
sum = a+b;
sub = a-b;
mult = a*b;
div = a/b;
mod = a%b;
print(sum)
print(sub)
print(mult)
print(div)
print(mod)

print("My Friend's", "Birthday", sep=".....")

#Variables - named memory location

# must start with '_' or letter
# cannot start with digit or special character

name = 'Yash'
_course = 'Btech'
print(name)
print(_course)

#Identifiers : The custom names that we give in any programming language

# can be given to - Variable, Function, Class
# cannot start with digit or special character same as variable

"""
Data Types -

Integer
String
Float
None
Boolean
List
Tuple
Dictionary
"""